services:
  vpl-jail:
    image: "jail-${VPL_BASE_DISTRO}-${VPL_INSTALL_LEVEL}"
    privileged: "${VPL_RUN_PRIVILEGED}"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.no_https
      args:
        - VPL_BASE_DISTRO
        - VPL_INSTALL_LEVEL
        - VPL_JAIL_PORT
        - VPL_JAIL_JAILPATH
    ports:
      - ${VPL_EXPOSE_PORT}:${VPL_JAIL_PORT}
