services:
  vpl-jail:
    environment:
      - VPL_BASE_DISTRO
      - VPL_INSTALL_LEVEL
      - VPL_RUN_PRIVILEGED
      - VPL_JAIL_JAILPATH
      - VPL_CERTIFICATES_DIR
      - VPL_JAIL_SSL_CERT_FILE
      - VPL_JAIL_SSL_KEY_FILE
      - VPL_HOST_SSL_DIRECTORY
      - VPL_JAIL_CERBOT_WEBROOT_PATH
      - VPL_EMAIL_FOR_CERBOT
      - VPL_SERVER_NAME
    image: "jail-${VPL_BASE_DISTRO}-${VPL_INSTALL_LEVEL}"
    privileged: ${VPL_RUN_PRIVILEGED}
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.letsencrypt
      args:
        - VPL_BASE_DISTRO=${VPL_BASE_DISTRO}
        - VPL_INSTALL_LEVEL=${VPL_INSTALL_LEVEL}
        - VPL_JAIL_PORT=${VPL_JAIL_PORT}
        - VPL_JAIL_SECURE_PORT=${VPL_JAIL_SECURE_PORT}
        - VPL_JAIL_JAILPATH=${VPL_JAIL_JAILPATH}
        - VPL_CERTIFICATES_DIR=${VPL_CERTIFICATES_DIR}
        - VPL_JAIL_SSL_CERT_FILE=${VPL_JAIL_SSL_CERT_FILE}
        - VPL_JAIL_SSL_KEY_FILE=${VPL_JAIL_SSL_KEY_FILE}
    volumes:
      - certbot_webroot:${VPL_JAIL_CERBOT_WEBROOT_PATH}:ro
      - type: bind
        source: ${VPL_HOST_SSL_DIRECTORY}
        target: ${VPL_CERTIFICATES_DIR}
        read_only: true
    ports:
      - "${VPL_EXPOSE_PORT}:${VPL_JAIL_PORT}"
      - "${VPL_EXPOSE_SECURE_PORT}:${VPL_JAIL_SECURE_PORT}"
  
  certbot_obtain_certificate:
    image: vpl_certbot
    build:
      context: .
      dockerfile: Dockerfile.certbot
    command: "/bin/sh -c 'certbot certonly -n --webroot --webroot-path /var/www -m ${VPL_EMAIL_FOR_CERBOT} --agree-tos -d ${VPL_SERVER_NAME}'"
    depends_on:
      vpl-jail:
        condition: service_started
    profiles: 
      - obtain_certificate
    volumes:
      - certbot_webroot:/var/www:rw
      - type: bind
        source: ${VPL_HOST_SSL_DIRECTORY}
        target: /etc/letsencrypt

  certbot_renew:
    image: vpl_certbot
    build:
      context: .
      dockerfile: Dockerfile.certbot
    command: "/bin/sh -c 'trap exit TERM; echo \"Checking to renew certificates every 12h\"; while :; do certbot renew; sleep 12h & wait $!; done;'"
    depends_on:
      vpl-jail:
        condition: service_started
    volumes:
      - certbot_webroot:/var/www:rw
      - type: bind
        source: ${VPL_HOST_SSL_DIRECTORY}
        target: /etc/letsencrypt

volumes:
  certbot_webroot:
