name: VPL jail server Build and Release (VPL Moodle Plugin)

on: [workflow_dispatch]

jobs:
  
    build:
        runs-on: ubuntu-22.04
        strategy:
          fail-fast: true
    
        steps:
          - name: Check out repository code
            uses: actions/checkout@v4
            with:
              path: ~
    
          - name: Install Dependencies
            run: sudo apt-get update && sudo apt-get install -y autoconf automake libtool
        
          - name: Prepare the Build
            run: |
              autoreconf -i
              aclocal
              autoheader
              autoconf
              automake
              ./configure
    
          - name: Build and Check
            run: make distcheck

          - name: Extract branch name
            id: branch
            run: |
                package_name=$(ls *.gz | head -n1)
                version=$(echo ${package_name#refs/heads/})
                echo "version=$version" >> "$GITHUB_OUTPUT"
                echo "package_name=$package_name"  >> "$GITHUB_OUTPUT"

          - name: Upload package
            uses: actions/upload-artifact@v2
            with:
              name: ${{ steps.branch.outputs.package_name }}
              path: ${{ steps.branch.outputs.package_name }}
              if-no-files-found: error
    release:
        needs: build
        runs-on: ubuntu-22.04
        strategy:
          fail-fast: false
        env:
          version: ${{ needs.build.result.package_name }}
          package_name: ${{ needs.build.result.version }}
        steps:
            - name: Download package
              uses: actions/download-artifact@v2
              with:
                name: ${{ env.package_name }}
                path: ${{ env.package_name }}
            - name: Create Release
              uses: actions/create-release@v1
              id: create_release
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: "V${{ env.version }}"
                release_name: "VPL-JAIL-SYSTEM V${{ env.version }}"
                draft: false
                prerelease: true
                body: |
                  "This is an automated build of VPL-JAIL-SYSTEM V$${{ env.version }}
                  generated through our Continuous Integration (CI) process.
                  Please be aware that this build is not an official release.
                  It is intended primarily for testing and development purposes.
                  Users should employ this build with the understanding that it has
                  not undergone the same level of testing as our official releases
                  and may contain bugs or unfinished features.

                  Use this build with caution and consider the potential risks before
                  deployment in a production environment."
            - name: Upload Release Asset
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: ${{ env.package_name }}
                asset_name: ${{ env.package_name }}
                asset_content_type: application/gzip 
